import json
import os
import argparse
import sys
import pandas as pd

def parse_args():
    parser = argparse.ArgumentParser(description="Generate safe training indices by filtering out high-influence indices from sorted.csv.")
    
    parser.add_argument(
        "--sorted_score_file", 
        type=str, 
        required=True, 
        help="Path to the sorted.csv file generated by write_selected_data."
    )
    parser.add_argument(
        "--train_files", 
        type=str, 
        nargs='+', 
        required=True, 
        help="List of paths to the original training files (JSONL)."
    )
    parser.add_argument(
        "--train_file_names", 
        type=str, 
        nargs='+', 
        required=True, 
        help="List of names for the training files (must match names used in write_selected_data)."
    )
    parser.add_argument(
        "--percentage", 
        type=float, 
        default=0.05, 
        help="The percentage of top-scoring data to exclude (e.g., 0.05 for 5%)."
    )
    parser.add_argument(
        "--output_dir", 
        type=str, 
        required=True, 
        help="Directory where the safe indices JSON will be saved."
    )
    
    return parser.parse_args()

def count_lines(filename):
    with open(filename, 'r', encoding='utf-8', errors='ignore') as f:
        return sum(1 for _ in f)

def main():
    args = parse_args()

    # --- Validation ---
    if len(args.train_files) != len(args.train_file_names):
        print("Error: The number of train files and train file names must match.")
        sys.exit(1)
        
    if not os.path.exists(args.sorted_score_file):
        print(f"Error: Sorted score file not found at {args.sorted_score_file}")
        sys.exit(1)

    # --- 1. Calculate Global Offsets ---
    # We need to map (file_name, local_index) -> global_index
    # Global index assumes files are concatenated in the order provided.
    
    print("Calculating file offsets...")
    file_offsets = {}
    file_line_counts = {}
    current_offset = 0
    
    for name, filepath in zip(args.train_file_names, args.train_files):
        if not os.path.exists(filepath):
            print(f"Error: Training file not found at {filepath}")
            sys.exit(1)
            
        line_count = count_lines(filepath)
        file_offsets[name] = current_offset
        file_line_counts[name] = line_count
        print(f"  - {name}: {line_count} lines (Offset: {current_offset})")
        current_offset += line_count

    total_lines = current_offset
    print(f"Total dataset size: {total_lines}")

    # --- 2. Read Sorted Scores ---
    print(f"Reading scores from: {args.sorted_score_file}")
    # Expecting CSV format: "file name, index, score"
    # Using pandas for robust CSV parsing, handling spaces after commas if present
    df = pd.read_csv(args.sorted_score_file, skipinitialspace=True)
    
    # Ensure columns are correct
    required_cols = {'file name', 'index', 'score'}
    if not required_cols.issubset(df.columns):
        print(f"Error: CSV is missing required columns. Found: {df.columns}")
        sys.exit(1)

    # --- 3. Determine Cutoff ---
    # The sorted.csv is already sorted descending (highest influence first).
    # We want to EXCLUDE the top P percent.
    
    num_bad = int(total_lines * args.percentage)
    print(f"Excluding top {args.percentage*100}% ({num_bad} samples)")

    # The dataframe is already sorted by score descending (from write_selected_data logic)
    # If not, we should sort it: df = df.sort_values(by='score', ascending=False)
    
    # Take the "Safe" portion (from index num_bad onwards)
    safe_df = df.iloc[num_bad:]

    # --- 4. Convert to Global Indices ---
    safe_indices = []
    
    print("Converting to global indices...")
    for _, row in safe_df.iterrows():
        fname = row['file name']
        local_idx = int(row['index'])
        
        if fname not in file_offsets:
            print(f"Warning: File name '{fname}' in CSV not found in provided arguments. Skipping.")
            continue
            
        global_idx = file_offsets[fname] + local_idx
        safe_indices.append(global_idx)

    # Sort indices for cleanliness (optional but recommended)
    safe_indices.sort()

    # --- 5. Save ---
    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    output_file = os.path.join(args.output_dir, "safe_training_indices.json")
    
    with open(output_file, "w") as f:
        json.dump(safe_indices, f)

    # Summary
    print("-" * 30)
    print(f"Total Data:      {total_lines}")
    print(f"Harmful Removed: {total_lines - len(safe_indices)}")
    print(f"Safe Remaining:  {len(safe_indices)}")
    print(f"Output Saved:    {output_file}")
    print("-" * 30)

if __name__ == "__main__":
    main()